mgService/urls.py
from django.conf.urls import url
from django.contrib import admin
from app import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    #url(r'^edit/(?P<zmiennaklucza>\d+)$', 'app.views.edit')
    #url(r'^new/', 'app.views.new')
    #url(r'', 'app.views.home', name = 'home'),

    url(r'^admin/', admin.site.urls),
    url(r'^pdfRepair/(?P<pkRepair>\d+)$', views.pdfRepair, name='pdfRepair'),
    url(r'^login/$', auth_views.login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page':'home'}, name='logout'),
    url(r'^newClient/', views.newClient, name='newClient'),
    url(r'^newVehicle/', views.newVehicle, name='newVehicle'),
    url(r'^newRepair/(?P<pkVehicle>\d+)$', views.newRepair, name='newRepair'),
    url(r'^newDefaultRepair/', views.newDefaultRepair, name='newDefaultRepair'),
    url(r'^editClient/(?P<pkClient>\d+)$', views.editClient, name='editClient'),
    url(r'^editVehicle/(?P<pkVehicle>\d+)$', views.editVehicle, name='editVehicle'),
    url(r'^editRepair/(?P<pkRepair>\d+)$', views.editRepair, name='editRepair'),
    url(r'^editDefaultRepair/(?P<pkDefaultRepair>\d+)$', views.editDefaultRepair, name='editDefaultRepair'),
    url(r'^delClient/(?P<pkClient>\d+)$', views.deleteClient, name='delClient'),
    url(r'^delVehicle/(?P<pkVehicle>\d+)$', views.deleteVehicle, name='delVehicle'),
    url(r'^delDefaultRepair/(?P<pkDefaultRepair>\d+)$', views.deleteDefaultRepair, name='delDefaultRepair'),
    url(r'^delRepair/(?P<pkRepair>\d+)$', views.deleteRepair, name='delRepair'),
    url(r'^manageClient/', views.manageClient, name='manageClient'),
    url(r'^manageDefaultRepair/(?P<pkDefaultRepair>\d+)$', views.manageDefaultRepair, name='manageDefaultRepair'),
    url(r'^manageDefaultRepair/', views.manageDefaultRepair, name='manageDefaultRepair'),
    url(r'^infoVehicle/(?P<pkVehicle>\d+)$', views.infoVehicle, name='infoVehicle'),
    url(r'', views.home, name='home'),

]

app/forms.py
from django import forms
from app.models import *
from django.forms import ModelForm, Textarea, CheckboxSelectMultiple, HiddenInput
from django.contrib.admin.widgets import *
from datetime import datetime

class ClientForm(ModelForm):
    name = forms.CharField(label="Imię", max_length=50,  required=False)
    surname = forms.CharField(label="Nazwisko", max_length=50)
    contact = forms.CharField(label="Kontakt", max_length=30, required=False)
    comment = forms.CharField(label="Uwagi", max_length=3000, required=False, widget=forms.Textarea(attrs={'rows': 3}))
    class Meta:
        model = Client
        fields = '__all__'

class VehicleForm(ModelForm):
    make = forms.CharField(label="Marka", max_length=20)
    model = forms.CharField(label="Model", max_length=20)
    engine = forms.CharField(label="Silnik", max_length=20, required=False)
    productionYear = forms.CharField(label="Rok produkcji", max_length=4, required=False)
    registrationNumber = forms.CharField(label="Numer rejestracyjny", max_length=10)
    vinNumber = forms.CharField(label="Numer VIN", max_length=17, required=False)
    owners = forms.ModelMultipleChoiceField(label="Właściciel", queryset=Client.objects.all())
    class Meta:
        model = Vehicle
        fields = '__all__'
        widgets = {
            'owners': FilteredSelectMultiple('klienci', False)
        }
    def clean_registrationNumber(self):
        return self.cleaned_data["registrationNumber"].upper()
    def clean_vinNumber(self):
        return self.cleaned_data["vinNumber"].upper()

class RepairForm(ModelForm):
    date = forms.DateField(label="Data")
    mileage = forms.IntegerField(label="Przebieg")
    comment = forms.CharField(label="Uwagi", max_length=3000, required=False, widget=forms.Textarea(attrs={'rows': 6}))
    doneDefaultRepairs = forms.ModelMultipleChoiceField(label="Wykonane naprawy", queryset=DefaultRepair.objects.all(), widget=forms.SelectMultiple())
    doneOtherRepairs = forms.CharField(label='Inne naprawy', max_length=1000, required=False, widget=forms.Textarea(attrs={'rows': 4}))
    #image = forms.ImageField(label="Zdjęcie", required=False, widget=forms.ClearableFileInput())
    vehicle = forms.ModelChoiceField(label="Pojazd", queryset=Vehicle.objects.all(), widget=forms.HiddenInput())
    class Meta:
        model = Repair
        #fields = '__all__'
        exclude = ('image',)
    def clean_date(self):
        repairDate = self.cleaned_data["date"]
        now = datetime.now().date()
        if now < repairDate:
            raise forms.ValidationError("Data naprawy musi być mniejsza lub równa dzisiejszej")
        return repairDate

class DefaultRepairForm(ModelForm):
    name = forms.CharField(label="Nazwa")
    class Meta:
        model = DefaultRepair
        fields = '__all__'

app/templates/app/client_edit.html
{%extends 'app/layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="page-header">
    <h2>Edycja klienta - {{ client.name }} {{ client.surname }}</h2>
</div>

<hr />

<form action="{% url 'editClient' client.id %}" method="post">
	{% csrf_token %}
	{{ form|crispy }}
	<input class="btn btn-success" type="submit" value="Zapisz"></input>
    <a class="btn btn-default" href="{% url 'manageClient' %}">Anuluj</a>
</form>

{% endblock content %}

app/templates/app/client_manage.html
{%extends "app/layout.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="modal fade" id="newClientModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="{% url 'newClient' %}" method="post">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Nowy klient</h4>
				</div>
				<div class="modal-body">
					{% csrf_token %}
					{{ form|crispy }}
				</div>
				<div class="modal-footer">
					<input type="submit" class="btn btn-success" value="Dodaj" />
					<button type=button class="btn btn-default" data-dismiss="modal">Anuluj</button>
				</div>
			</form>
		</div>
	</div>
</div>

<div class="modal fade" id="deleteClientModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Usunięcie danych klienta</h4>
			</div>
			<div class="modal-body">
				Czy jesteś pewien, że chcesz usunąć wszystkie dane klienta? 
			</div>
			<div class="modal-footer">
				<button type=button class="btn btn-default" data-dismiss="modal">Anuluj</button>
				<a id="deleteClientConfirmButton" class="btn btn-danger" href="#">Usuń</a>
			</div>
		</div>
	</div>
</div>

<div class="page-header">
    <h2>Lista klientów</h2>
    <button id="newClientButton" class="btn btn-success btn-lg" data-toogle="modal" data-target="#newClientModal"><i class="fa fa-plus fa-lg" aria-hidden="true"></i> Dodaj klienta</button>
</div>

<hr />

<table id="manageClientTable" class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Nazwisko i imię</th>
			<th>Kontakt</th>
			<th>Notatka</th>
			<th>Pojazdy</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
    {% for client in allClients %}
	    <tr>
		    <td>{{ client }}</td>
		    <td>{{ client.contact }}</td>
		    <td>{{ client.comment }}</td>
		    <td>
			    {% for vehicle in client.getVehicles %}
				    <a href="{% url 'infoVehicle' vehicle.id %}">{{ vehicle }} </a>
				    </br>
			    {% endfor %}
		    </td>
		    <td class="td-buttons">
			    <a class="btn btn-primary" href="{% url 'editClient' client.id %}"><i class="fa fa-pencil fa-lg"></i> Edytuj</a>
                <button class="deleteClientButton btn btn-danger" data-toogle="modal" data-target="#deleteClientModal" data-href="{% url 'delClient' client.id %}"><i class="fa fa-trash-o fa-lg"></i> Usuń</button>
		    </td>
	    </tr>
    {% endfor %}
    </tbody>
</table>

{% if showForm == True %}
    <script>
        showModal('#newClientModal');
    </script>
{% endif %}

{% endblock content %}

app/templates/app/client_new.html
{%extends 'app/layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form action="newClient/" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type='submit' value="Dodaj" class="btn btn-success">
    <a class="btn btn-default" href="{% url 'home' %}">Anuluj</a>
</form>

{% endblock content %}

app/templates/app/defaultRepair_manage.html
{% extends "app/layout.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="modal fade" id="newDefaultRepairModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="{% url 'newDefaultRepair' %}" method="post">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Nowa standardowa naprawa</h4>
				</div>
				<div class="modal-body">
					{% csrf_token %}
					{{ form|crispy }}
				</div>
				<div class="modal-footer">
					<input type="submit" class="btn btn-success" value="Dodaj" />
					<button type=button class="btn btn-default" data-dismiss="modal">Anuluj</button>
				</div>
			</form>
		</div>
	</div>
</div>

<div class="modal fade" id="deleteDefaultRepairModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Usunięcie standardowej naprawy</h4>
			</div>
			<div class="modal-body">
				Czy jesteś pewien, że chcesz usunąć tę standardową naprawę? 
			</div>
			<div class="modal-footer">
				<button type=button class="btn btn-default" data-dismiss="modal">Anuluj</button>
				<a id="deleteDefaultRepairConfirmButton" class="btn btn-danger" href="#">Usuń</a>
			</div>
		</div>
	</div>
</div>

<div class="page-header">
    <h2>Lista standardowych usług</h2>
    <button id="newDefaultRepairButton" class="btn btn-success btn-lg" data-toogle="modal" data-target="#newDefaultRepairModal"><i class="fa fa-plus fa-lg" aria-hidden="true"></i> Dodaj naprawę</button>
</div>

<hr />

<table id="manageDefaultRepairTable" class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Nazwa</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
    {% for repair in allRepairs %}
        {% if repair.id == idRepair %}
		    <tr>
			    <form role="form" method="post" action="{% url 'editDefaultRepair' repair.id %}">
				    {% csrf_token %}
				    <td>{{ form.name }}</td>
				    <td class="td-buttons">
					    <input type="submit" class="btn btn-success" value="Zapisz" ></input>
					    <a class="btn btn-default" href="{% url 'manageDefaultRepair' %}">Anuluj</a>
				    </td>
			    </form>
		    </tr>
        {% else %}
	        <tr>
		        <td>{{ repair.name }}</td>
    		    <td class="td-buttons">
			        <a class="btn btn-primary" href="{% url 'manageDefaultRepair' repair.id %}"><i class="fa fa-pencil fa-lg"></i> Edytuj</a>
                    <button class="deleteDefaultRepairButton btn btn-danger" data-toogle="modal" data-target="#deleteDefaultRepairModal" data-href="{% url 'delDefaultRepair' repair.id %}"><i class="fa fa-trash-o fa-lg"></i> Usuń</button>
		        </td>
	        </tr>
        {% endif %}
    {% endfor %}
    </tbody>
</table>

{% if showForm == True %}
    <script>
        showModal('#newDefaultRepairModal');
    </script>
{% endif %}

{% endblock content %}

app/templates/app/index.html
{%extends "app/layout.html" %}
{% load crispy_forms_tags %}

{% block content %}

<div class="modal fade" id="newVehicleModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<form action="{% url 'newVehicle' %}" method="post">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal">&times;</button>
					<h4 class="modal-title">Nowy pojazd</h4>
				</div>
				<div class="modal-body">
					{% csrf_token %}
					{{ form|crispy }}
				</div>
				<div class="modal-footer">
					<input type="submit" class="btn btn-success" value="Dodaj" />
					<button type=button class="btn btn-default" data-dismiss="modal">Anuluj</button>
				</div>
			</form>
		</div>
	</div>
</div>

<div class="page-header">
    <h2>Lista pojazdów</h2>
    <button id="newVehicleButton" class="btn btn-success btn-lg" data-toogle="modal" data-target="#newVehicleModal"><i class="fa fa-plus fa-lg" aria-hidden="true"></i> Dodaj pojazd</button>
</div>

<hr />

<table id="indexTable" class="table table-striped table-hover">
	<thead>
		<tr>
			<th>Właściciel</th>
			<th>Numer rejestracyjny</th>
			<th>Marka</th>
			<th>Model</th>
			<th>Silnik</th>
			<th>Rok</th>
			<th>Przebieg [km]</th>
			<th>Numer VIN</th>
		</tr>
	</thead>
	<tbody>
    {% for vehicle in allVehicles %}
        <tr data-href="{% url 'infoVehicle' vehicle.id %}" class="tr-link">
	        <td>{% for owner in vehicle.owners.all %}{{ owner }}<br/>{% endfor %}</td>
	        <td>{{ vehicle.registrationNumber }}&nbsp;
                {% if vehicle.checkOilByMileage != None %} 
                    <span class="label label-warning"><i class="fa fa-exclamation-triangle" aria-hidden="true"></i></span>
                {% endif %}
            </td>
	        <td>{{ vehicle.make }}</td>
	        <td>{{ vehicle.model }}</td>
	        <td>{{ vehicle.engine }}</td>
	        <td>{{ vehicle.productionYear }}</td>
	        <td>{{ vehicle.getMileage }}</td>
	        <td>{{ vehicle.vinNumber }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% if showForm == True %}
    <script>
        showModal('#newVehicleModal');
    </script>
{% endif %}

{% endblock content %}

app/templates/app/layout.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="apple-touch-icon" href="apple-touch-icon.png">

        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-multiselect.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-datepicker.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <style>
            body {
                padding-top: 50px;
                padding-bottom: 20px;
            }
            td {
              padding: 0 10px 10px 0;
              line-height: 1.6 !important;
            }
            .tr-link {
              cursor: pointer;
            }
            .td-buttons {
                text-align: right;
            }
            input#id_registrationNumber, input#id_vinNumber { 
                text-transform: uppercase;
            }
            input[type=search] { 
                display: inline !important;
                width: inherit !important;
            }
            div.dataTables_length select { 
                display: inline !important;
                width: inherit !important;
            }
            .span-login {
                color: white;
                margin-right: 15px;
            }
            .page-header > button, .page-header > a {
                float: right;
                margin-left: 10px;
            }
            .page-header > h2, .page-header > h3 {
                display: inline-block;
            }
        </style>

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
        <script src="{% static 'js/vendor/jquery-1.11.2.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap-multiselect.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap-datepicker.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap-datepicker.pl.min.js' %}"></script>
        <script src="{% static 'js/vendor/jquery.dataTables.min.js' %}"></script>
        <script type="text/javascript">
            function showModal(modalID) {
                $(modalID).modal('show');
            }
        </script>



    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">MGService</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="{% url 'home' %}">Pojazdy</a>
                </li>
                <li><a href="{% url 'newVehicle' %}"><i class="fa fa-car" aria-hidden="true"></i><i class="fa fa-plus" aria-hidden="true"></i></a>
                </li>
                <li><a href="{% url 'manageClient' %}">Klienci</a>
                </li>
                <li><a href="{% url 'newClient' %}"><i class="fa fa-user" aria-hidden="true"></i><i class="fa fa-plus" aria-hidden="true"></i></a>
                </li>
                <li><a href="{% url 'manageDefaultRepair' %}">Usługi</a>
                </li>
                <li><a href="#"><i class="fa fa-wrench" aria-hidden="true"></i><i class="fa fa-plus" aria-hidden="true"></i></a>
                </li>
            </ul>
          {% if user.is_authenticated %}
            <form class="navbar-form navbar-right" role="form" method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <div class="form-group">
                <span class="span-login">Zalogowany jako: {{user.username}} </span>
              </div>
              <input type="hidden" name="next" value={{next}} />
              <button type="submit" class="btn btn-success" value="sign-in" >Wyloguj</button>
            </form>
          {%  else %}
            <form class="navbar-form navbar-right" role="form" method="post" action="{% url 'django.contrib.auth.views.login' %}">
              {% csrf_token %}
              <div class="form-group">
                <input type="text" placeholder="Email" class="form-control" name="username" id="id_username">
              </div>
              <div class="form-group">
                <input type="password" placeholder="Password" class="form-control" name="password" id="id_password" maxlength="30">
              </div>
              <input type="hidden" name="next" value={{next}} />
              <button type="submit" class="btn btn-success" value="sign-in" >Zaloguj</button>
            </form>
          {% endif %}
        </div><!--/.navbar-collapse -->
      </div>
    </nav>

      <div class="container">
        <!-- Example row of columns -->
        <div class="row">

          {% block content %}
          {% endblock content %}

        </div>
      </div>

      <hr>

      <footer class="container">
        <div class="row">
          <p>&copy; MGService 2016</p>
        </div>
      </footer>
    </div> <!-- /container -->        
        
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>
        <script src="{% static 'js/main.js' %}"></script>


<!-- ===================== moje skrypty================================== -->
<script>
    var dataTablesGlossary = {
        "processing": "Przetwarzanie...",
        "search": "Szukaj:",
        "lengthMenu": "Pokaż _MENU_ pozycji",
        "info": "Pozycje od _START_ do _END_ z _TOTAL_ łącznie",
        "infoEmpty": "Pozycji 0 z 0 dostępnych",
        "infoFiltered": "(filtrowanie spośród _MAX_ dostępnych pozycji)",
        "infoPostFix": "",
        "loadingRecords": "Wczytywanie...",
        "zeroRecords": "Nie znaleziono pasujących pozycji",
        "emptyTable": "Brak danych",
        "paginate": {
            "first": "Pierwsza",
            "previous": "Poprzednia",
            "next": "Następna",
            "last": "Ostatnia"
        },
        "aria": {
            "sortAscending": ": aktywuj, by posortować kolumnę rosnąco",
            "sortDescending": ": aktywuj, by posortować kolumnę malejąco"
        }
    }

  $(document).ready(function(){
    $('#indexTable').dataTable({
        "language": dataTablesGlossary,
        "pageLength": 25
    });

    $('#indexTable tr[data-href]').on("click", function() {
        document.location = $(this).data('href');
    });

    $('#infoVehicleTable').dataTable({
        "ordering": false,
        "language": dataTablesGlossary,
        "pageLength": 25
    });

    $('#manageClientTable').dataTable({
        "language": dataTablesGlossary,
        "pageLength": 25
    });

    $('#manageDefaultRepairTable').dataTable({
        "language": dataTablesGlossary,
        "ordering": false,
        "pageLength": 25
    });

    $('input[type=search]').addClass('textinput form-control');
    $('div.dataTables_length select').addClass('form-control');

    
    var multiselectOptions = {
        buttonWidth: '100%',
        enableFiltering: true,
        filterPlaceholder: 'Szukaj...',
        nonSelectedText: 'Wybierz',
        nSelectedText: ' wybranych opcji',
        numberDisplayed: 10
    }
    $('#id_owners').multiselect(multiselectOptions);
    $('#id_doneDefaultRepairs').multiselect(multiselectOptions);

    $('#id_date').datepicker({
        format: "dd.mm.yyyy",
        endDate: "0d",
        maxViewMode: 2,
        todayBtn: "linked",
        language: "pl",
        orientation: "bottom auto",
        autoclose: true,
        todayHighlight: true
    });

  });

$(".doneOtherRepairsDiv").each(function () {
    var text = $(this).html().replace("\n", "<br>");
    $(this).html(text);
});

$('#newRepairButton').on('click', function(){
    $('#newRepairModal').modal();
});

$('#newDefaultRepairButton').on('click', function(){
    $('#newDefaultRepairModal').modal();
});

$('#newClientButton').on('click', function(){
    $('#newClientModal').modal();
});

$('#newVehicleButton').on('click', function () {
    $('#newVehicleModal').modal();
});

$('#deleteVehicleButton').on('click', function () {
    $('#deleteVehicleModal').modal();
});

$('.deleteRepairButton').on('click', function () {
    $('#deleteRepairModal').modal();
    var newHref = $(this).data('href');
    $('#deleteRepairConfirmButton').attr('href', newHref);
});

$('.deleteDefaultRepairButton').on('click', function () {
    $('#deleteDefaultRepairModal').modal();
    var newHref = $(this).data('href');
    $('#deleteDefaultRepairConfirmButton').attr('href', newHref);
});

$('.deleteClientButton').on('click', function () {
    $('#deleteClientModal').modal();
    var newHref = $(this).data('href');
    $('#deleteClientConfirmButton').attr('href', newHref);
});

function showModal(modalID) {
    $(modalID).modal({ show: true });
}

</script>

    </body>
</html>

app/templates/app/repair_edit.html
{%extends 'app/layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="page-header">
    <h2>Edycja wpisu naprawy - {{ repair.vehicle }}</h2>
</div>

<hr />

<form action="{% url 'editRepair' repair.id %}" method="post">
	{% csrf_token %}
	{{ form|crispy }}
	<input class="btn btn-success" type="submit" value="Zapisz"></input>
    <a class="btn btn-default" href="{% url 'infoVehicle' repair.vehicle.id %}">Anuluj</a>
</form>

{% endblock content %}

app/templates/app/vehicle_edit.html
{%extends 'app/layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

<div class="page-header">
    <h2>Edycja danych pojazdu - {{ vehicle }}</h2>
</div>

<hr />

<form action="{% url 'editVehicle' vehicle.id %}" method="post">
	{% csrf_token %}
	{{ form|crispy }}
	<input class="btn btn-success" type="submit" value="Zapisz"></input>
    <a class="btn btn-default" href="{% url 'infoVehicle' vehicle.id %}">Anuluj</a>
</form>

{% endblock content %}

app/templates/app/vehicle_new.html
{%extends 'app/layout.html' %}
{% load crispy_forms_tags %}

{% block content %}

<form action="new/" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type = 'submit' value = "Dodaj">
</form>

{% endblock content %}